Repository kubernetes-client/c, pull requests merged in 2021-09, with the labels that each got.

#78 Add examples, and pre and post CMake building scripts
  .github/workflows/build.yml
  README.md
  examples/CMakeLists.txt
  examples/list_pod/CMakeLists.txt
  examples/list_pod/main.c
  kubernetes/CMakeLists.txt
  kubernetes/PostTarget.cmake
  kubernetes/PreTarget.cmake
  kubernetes/README.md
Labels: approved, lgtm, size/L, cncf-cla: yes

#79 [Exec] Pod exec in cluster
  examples/exec_pod/main.c
  kubernetes/websocket/wsclient.c
  kubernetes/websocket/wsclient.h
Labels: approved, lgtm, cncf-cla: yes, size/M

#84 MacOs Installation Adaptations
  kubernetes/config/incluster_config.c
  kubernetes/config/kube_config.c
Labels: approved, lgtm, cncf-cla: yes, size/S

#85 Add vcpkg documentations
  README.md
Labels: approved, lgtm, cncf-cla: yes, size/S

#86 [Doc] Reorganize readme for vcpkg
  README.md
  docs/vcpkg.md
Labels: approved, lgtm, cncf-cla: yes, size/M
