Repository kubernetes-client/c, pull requests merged in 2022-08, with the labels that each got.

#133 Add the Valgrind memory check for examples
  .github/workflows/build.yml
  examples/Makefile
  examples/configmap/Makefile
  examples/create_pod/Makefile
  examples/delete_pod/Makefile
  examples/exec_pod/Makefile
  examples/generic/Makefile
  examples/list_pod/Makefile
  examples/list_secret/Makefile
  examples/multi_thread/Makefile
Labels: approved, lgtm, size/L, cncf-cla: yes

#135 Wait for the pod to terminate cleanly after deleting the pod during testing
  examples/Makefile
Labels: approved, lgtm, size/XS, cncf-cla: yes

#140 Resolve cpp keyword conflict
  kubernetes/config/kube_config_model.c
  kubernetes/config/kube_config_model.h
  kubernetes/config/kube_config_yaml.c
Labels: approved, lgtm, cncf-cla: yes, size/S
