Repository kubernetes-client/c, pull requests merged in 2023-01, with the labels that each got.

#165 Update config.h.in to be more clear
  kubernetes/config.h.in
Labels: approved, lgtm, size/XS, cncf-cla: yes

#167 Load user certificates by file path
  kubernetes/config/kube_config_yaml.c
Labels: approved, lgtm, cncf-cla: yes, size/M

#169 Fix memory leak when kubeconfig is invalid
  examples/Makefile
  examples/list_pod_with_invalid_kubeconfig/.gitignore
  examples/list_pod_with_invalid_kubeconfig/Makefile
  examples/list_pod_with_invalid_kubeconfig/main.c
  kubernetes/config/kube_config_yaml.c
Labels: approved, lgtm, size/L, cncf-cla: yes
